storage:
  # Some things will be ignored if not applicable for the database type
  # Allowed values: H2 , MySQL or JSON
  type: JSON
  host: localhost
  port: 3306
  name: xkingdoms
  username: mc
  password: p@ssword
  max-connections: 8
default: true

vanish:
  # apply night vision when a player vanishes
  apply-night-vision: true
  # do not remove night vision when unvanishing if the player already got it before vanishing
  no-night-vision-removal: true
  # will vanished players be able to see other vanished players?
  players-will-see-each-other: true
  # when doing a fake quit or join, send the quit or join message to yourself too?
  send-message-to-self: true