# Certain values will be ignored if not applicable for the database type
database:
  type: H2
  host: localhost
  port: 3306
  name: xkingdoms
  username: mc
  password: p@ssword
  max-connections: 8
default: true

vanish:
  # apply nightvision when a player vanishes
  apply-nightvision: true
  # will vanished players be able to see other vanished players?
  players-will-see-each-other: true