storage:
  # Some things will be ignored if not applicable for the database type
  # Allowed values: SQLITE, MySQL or JSON
  type: SQLITE
  host: localhost
  port: 3306
  name: xkingdoms
  username: mc
  password: p@ssword
default: true

vanish:
  # apply night vision when a player vanishes
  apply-night-vision: true
  # will vanished players be able to see other vanished players?
  see-other-vanished-players: true
  # when doing a fake quit or join, send the quit or join message to yourself too?
  send-message-to-self: true
  # then color of the bossbar which shows up when vanishing
  bossbar-color: purple